### ISSUE TITLE
Add `svgo` to optimize the SVG Sprite

### ISSUE THREAD

**Issue by stramel** [alexanderson1993/svg-icons-cli#1]
Thanks for this tool! We just started using it and it's working great! I'm currently doing `svgo` as a separate process after the fact. Would you be open to adding `svgo` as part of this tooling? Possibly adding as opt-in through an `--optimize` flag?

**Comment by stramel** [comment]
Thank you @alexanderson1993! Greatly appreciated!

**Comment by alexanderson1993** [comment]
Thanks for the suggestion!
