### ISSUE TITLE
--optimize breaks sprite generation with svgo 3.2.0

### ISSUE THREAD

**Issue by rphlmr** [alexanderson1993/svg-icons-cli#4]
Hello,

A fresh install with SVGO 3.2.0 breaks the generation of the sprite with `--optimize`.
To make it work again, we need a `svgo.config.js` (or apply a default config to `optimize` in your CLI).

```js
/** @type {import("svgo").Config} */
module.exports = {
    plugins: [
        {
            name: "preset-default",
            params: {
                overrides: {
                    removeHiddenElems: false,
                    cleanupIds: false,
                    convertPathData: {
                        floatPrecision: 5,
                    },
                },
            },
        },
    ],
};
```

I hope it helps other people who struggle with that 😅

**Comment by alexanderson1993** [comment]
I believe this was fixed in 0.0.6, but I forgot to update the main branch or note that here. Closing, let me know if it's still not working.
